apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine
      workingDir: $(workspaces.source.path)
      script: |
        echo "Cleaning workspace"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.9
      workingDir: $(workspaces.source.path)
      script: |
        echo "Running tests"
        python -m nose || true

